server:
  port: 9901
spring:
  application:
    name: tensquare-base
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    //url: jdbc:mysql://10.211.55.8:3306/tensquare_base?characterEncoding=utf-8
    url: jdbc:mysql://localhost/elem?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    show-sql: true
    database: mysql
  rabbitmq:
    host: 10.211.55.8
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
ip: 127.0.2.1
